-- Create ITEM Table
CREATE TABLE ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NUMBER INT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    AVAILABLE_QUANTITY INT DEFAULT 0,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL
);

-- Create CUSTOMER_ORDER Table
CREATE TABLE CUSTOMER_ORDER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    SHIPPING_INFO_ID_FK INT,
    PAYMENT_INFO_ID_FK INT,
    STATUS VARCHAR(255) DEFAULT 'New'
);

-- Create CUSTOMER_ORDER_LINE_ITEM Table
CREATE TABLE CUSTOMER_ORDER_LINE_ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    CUSTOMER_ORDER_ID_FK INT,
    FOREIGN KEY (CUSTOMER_ORDER_ID_FK) REFERENCES CUSTOMER_ORDER(ID)
);

-- Create PAYMENT_INFO Table
CREATE TABLE PAYMENT_INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CARD_NUMBER VARCHAR(16) NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    CARDHOLDER_NAME VARCHAR(255) NOT NULL,
    BILLING_ADDRESS VARCHAR(255)
);

-- Create SHIPPING_INFO Table
CREATE TABLE SHIPPING_INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENT_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    PHONE_NUMBER VARCHAR(15)
);
