-- Create ITEM Table
CREATE TABLE ITEM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    itemNumber INT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    availableQuantity INT DEFAULT 0,
    unitPrice DOUBLE NOT NULL
);

-- Create CUSTOMER_ORDER Table
CREATE TABLE CUSTOMER_ORDER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customerName VARCHAR(255) NOT NULL,
    customerEmail VARCHAR(255) NOT NULL,
    shippingInfoIdFk INT,
    paymentInfoIdFk INT,
    status VARCHAR(255) DEFAULT 'New'
);

-- Create CUSTOMER_ORDER_LINE_ITEM Table
CREATE TABLE CUSTOMER_ORDER_LINE_ITEM (
    id INT AUTO_INCREMENT PRIMARY KEY,
    itemId INT NOT NULL,
    itemName VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    customerOrderIdFk INT,
    FOREIGN KEY (customerOrderIdFk) REFERENCES CUSTOMER_ORDER(id)
);

-- Create PAYMENT_INFO Table
CREATE TABLE PAYMENT_INFO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cardNumber VARCHAR(16) NOT NULL,
    expirationDate DATE NOT NULL,
    cardholderName VARCHAR(255) NOT NULL,
    cvv VARCHAR(4) NOT NULL
);

-- Create SHIPPING_INFO Table
CREATE TABLE SHIPPING_INFO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zipCode VARCHAR(10) NOT NULL
);
